<html>
    <body>
        <header>
            <?php
                $this->title = 'Accueil GESTION clinique';
                $this->headTitle($this->title);
            ?>
        </header>
        
        <section>
            <article>
                <h2>Bienvenue sur le site de gestion de cliniques vétérinaires !</h2>
                <p>
                    Ce site sert à prendre des rendez-vous chez le vétérinaire.<br>
                    Pour pouvoir prendre un rendez-vous il faut d'abord enregistrer l'animal<br>
                    et le propriétaire. Puis il faut définire la clinique où va se passer<br>
                    cette consultation avec l'heure.
                </p>     
                <figure>
                    <img src= "../public/img/visite-annuelle-veterinaire-chien.jpg"  alt="Affichage image vétérinaire">
                </figure>            
            </article>
        </section>
    </body>
</html>