<?php
$this->title = 'Les Vétérinaires';
$this->headTitle($this->title);
?>

<?php
$this->tabContainer()->captureStart('tabcontainer', array(), array());
$this->contentPane()->captureStart('tab1', array(), array('title' => 'Les vétérinaires'));
?>
<p><a href="<?php
echo $this->url(array('controller' => 'veterinaire',
    'action' => 'ajouter'));
?>">Ajouter un vétérinaire</a></p>


<!--<form action="postIt" id="myform">-->

<script type="text/javascript" >    
    var structure = [ 
        { field: 'idPersonne', name : 'ID', width: '50px' },
        { field: 'nomPersonne', name : 'Nom', width: '100px' },
        { field: 'prenomPersonne', name : 'Prenom', width: '100px' },
        { field: 'dateNaissancePersonne', name : 'Date naissance', width: '200px'},
        { field: 'telFixePersonne', name : 'Telephone Fixe', width: '100px' },
        { field: 'telMobilePersonne', name : 'Telephone Mobile', width: '100px' },
        { field: 'mailPersonne', name : 'Mail', width: '200px'},
        { field: 'typePersonne', name : 'Type', width: '100px' },
        { field: 'Adresse_idAdresse', name : 'Adresse', width: '200px'},
    ]; 
</script>


<span dojoType="dojox.data.QueryReadStore" jsId="idPersonne" url="/v_esp/public/veterinaire/indexjson"></span>
<div id="grid1" data-dojo-id="grid2" dojoType="dojox.grid.DataGrid" 
     data-dojo-props="store:idPersonne,
     structure:'structure'  ,
     clientSort:true,
     rowSelector:'20px'"
     style=" height: 260px;"></div>

<div data-dojo-type="dijit/form/Form" id="modifier" data-dojo-id="myForm"
     encType="multipart/form-data" action="veterinaire/modifier" method="GET">
    <script type="dojo/on" data-dojo-event="submit">
        dojo.require("dojo.NodeList-manipulate");
        var items = grid2.selection.getSelected();
        if(items.length){            
            dojo.forEach(items, function(selectedItem){
                if(selectedItem !== null){
                    attribute = 'idPersonne';
                    var value = grid2.store.getValues(selectedItem, attribute);                    
                    var idPersonne = dojo.query("#id").val(value);
                } 
            }); 
        }
    </script>

    <input type="hidden" id="id" name="idPersonne"  value="" />
    <button data-dojo-type="dijit/form/Button"             
            type="submit" >
        Modifier
    </button>

    <button data-dojo-type="dijit/form/Button"             
            type="button">
        Supprimer
        <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
            require(["dijit/registry"], function(registry){
            registry.byId("dialog").show();
            });
        </script>
    </button>

    <div id="dialog" title="Suppression" data-dojo-id="dialog" data-dojo-type="dijit/Dialog">
        <script type="dojo/on" data-dojo-event="show">            
            dojo.require("dojo.NodeList-manipulate");
            var items = grid2.selection.getSelected();
            if(items.length){            
                dojo.forEach(items, function(selectedItem){
                    if(selectedItem !== null){
                        var idPersonne = grid2.store.getValues(selectedItem, 'idPersonne');
                        dojo.query("#idPersonneS").val(idPersonne);
                        var detaille = idPersonne + ' ';
                        dojo.query("#detaille").html(detaille);                      
                    } 
                }); 
            }
        </script>
        <p>Êtes-vous sûr de vouloir supprimer <div id="detaille"></div>
        </p>
        <form action="<?php echo $this->url(array('action' => 'supprimer')); ?>" method="post">
            <div>
                <input type="hidden" id ="idPersonneS" name="idPersonneS" value="" />
                <button data-dojo-type="dijit/form/Button"  type="submit" name="supprimer" value="Oui">
                    Oui
                </button>
                <button data-dojo-type="dijit/form/Button" 
                        type="button" data-dojo-props="onClick:function(){dialog.hide();}"
                        id="cancel" >Non</button>
            </div>
        </form>
    </div>
</div>






<?php
echo $this->contentPane()->captureEnd('tab1');
echo $this->tabContainer()->captureEnd('tabcontainer');
?>



