<ul id="nav">
    <li class="current_page_item"><a href="<?php echo $this->baseUrl() ?>/index" >Accueil</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/clinique" >Cliniques</a></li>
       <li><a href="<?php echo $this->baseUrl() ?>/veterinaire" >Vétérinaires</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/rendezvous">Rendez-vous</a></li>
     <li><a href="<?php echo $this->baseUrl() ?>/Animaux">Animaux</a></li>
    <li><a href="<?php echo $this->baseUrl() ?>/personne">Personnes</a></li>
</ul>
